// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "adjustcontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CAdjustControl

IMPLEMENT_DYNCREATE(CAdjustControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAdjustControl properties

/////////////////////////////////////////////////////////////////////////////
// CAdjustControl operations

void CAdjustControl::SetDevice(LPDISPATCH DevAcc, long Devices)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 DevAcc, Devices);
}

void CAdjustControl::CloseDevice()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CAdjustControl::Busy()
{
	BOOL result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CAdjustControl::IsWarning(long StatusCode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		StatusCode);
	return result;
}

BOOL CAdjustControl::IsError(long StatusCode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		StatusCode);
	return result;
}

CString CAdjustControl::Message(long StatusCode)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		StatusCode);
	return result;
}

void CAdjustControl::Refresh()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAdjustControl::SetDatasource(LPUNKNOWN Source, long Devices)
{
	static BYTE parms[] =
		VTS_UNKNOWN VTS_I4;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Source, Devices);
}
