#if !defined(AFX_ADJUSTCONTROL_H__A46E840D_035C_45D0_A4CD_2DFFC3E4A94D__INCLUDED_)
#define AFX_ADJUSTCONTROL_H__A46E840D_035C_45D0_A4CD_2DFFC3E4A94D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAdjustControl wrapper class

class CAdjustControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAdjustControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa22d386e, 0x6cda, 0x11d2, { 0xb2, 0x36, 0x0, 0x10, 0x4b, 0x9e, 0x58, 0x6e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetDevice(LPDISPATCH DevAcc, long Devices);
	void CloseDevice();
	BOOL Busy();
	BOOL IsWarning(long StatusCode);
	BOOL IsError(long StatusCode);
	CString Message(long StatusCode);
	void Refresh();
	void SetDatasource(LPUNKNOWN Source, long Devices);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ADJUSTCONTROL_H__A46E840D_035C_45D0_A4CD_2DFFC3E4A94D__INCLUDED_)
