// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "analysiseditor.h"

/////////////////////////////////////////////////////////////////////////////
// CAnalysisEditor

IMPLEMENT_DYNCREATE(CAnalysisEditor, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAnalysisEditor properties

/////////////////////////////////////////////////////////////////////////////
// CAnalysisEditor operations

void CAnalysisEditor::SetSequence(LPDISPATCH Datasource, BOOL Alpha, BOOL ReadOnly)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_BOOL VTS_BOOL;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Datasource, Alpha, ReadOnly);
}

void CAnalysisEditor::GetSequenceChanges(LPDISPATCH Datasource)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Datasource);
}

BOOL CAnalysisEditor::IsChanged()
{
	BOOL result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAnalysisEditor::NewSequence(BOOL Alpha, BOOL NAI)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Alpha, NAI);
}

BOOL CAnalysisEditor::IsWarning(long StatusCode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		StatusCode);
	return result;
}

BOOL CAnalysisEditor::IsError(long StatusCode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		StatusCode);
	return result;
}

CString CAnalysisEditor::Message(long StatusCode)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		StatusCode);
	return result;
}
