#if !defined(AFX_REPORTVIEWER_H__2DE8BEF9_ABB6_47F0_8AE2_4CAD9D65B22D__INCLUDED_)
#define AFX_REPORTVIEWER_H__2DE8BEF9_ABB6_47F0_8AE2_4CAD9D65B22D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CReportViewer wrapper class

class CReportViewer : public CWnd
{
protected:
	DECLARE_DYNCREATE(CReportViewer)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5ec32872, 0xbcac, 0x11d1, { 0xab, 0x1e, 0x0, 0x20, 0xaf, 0x30, 0x27, 0x38 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetRefFont(LPDISPATCH newValue);
	void SetFont(LPDISPATCH newValue);
	COleFont GetFont();
	long GetWindow();
	void Clear();
	void PrintOut(LPCTSTR Printer);
	void SetBorderStyle(long nNewValue);
	long GetBorderStyle();
	void Copy();
	void CopyAll();
	void LoadText(LPCTSTR Filename, long* Offset, long Length);
	void LoadRTF(LPCTSTR Filename);
	void SaveText(LPCTSTR Filename, BOOL Overwrite);
	void SaveRTF(LPCTSTR Filename, BOOL Overwrite);
	void ExecuteReport(LPDISPATCH Datasource, LPCTSTR Template, LPCTSTR Section, long Options, float Sigma, LPCTSTR ActivityUnits, float ActivityMultiplier);
	BOOL IsWarning(long StatusCode);
	BOOL IsError(long StatusCode);
	CString Message(long StatusCode);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_REPORTVIEWER_H__2DE8BEF9_ABB6_47F0_8AE2_4CAD9D65B22D__INCLUDED_)
