//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Example.rc
//
#define IDTIMER1                        1
#define IDTIMER2                        2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIALOG_WINGAA               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDD_DIALOG_ACQSETUP             133
#define IDD_DIALOG_ADJUST               134
#define IDD_DIALOG_PREFERENCE           136
#define IDD_DIALOG_ANALYSIS             137
#define IDD_DIALOG_SAMPLEINFO           140
#define IDD_DIALOG_CAL                  143
#define IDC_MVC1                        1000
#define IDC_RADIO_LIVE                  1002
#define IDC_RADIO_REAL                  1003
#define IDC_EDIT_TIME                   1004
#define IDC_RADIO_NONE                  1005
#define IDC_RADIO_INTEGRAL              1006
#define IDC_RADIO_AREA                  1007
#define IDC_RADIO_COUNTS                1008
#define IDC_EDIT_VALUE                  1009
#define IDC_EDIT_START                  1010
#define IDC_EDIT_STOP                   1011
#define IDC_BUTTON_ROI                  1012
#define IDC_BUTTON_HV                   1013
#define IDC_ADJUSTCONTROL1              1014
#define IDC_BUTTON_SPEC                 1015
#define IDC_BUTTON_BKGND                1016
#define IDC_BUTTON_ROI1                 1017
#define IDC_BUTTON_ROI2                 1018
#define IDC_BUTTON_ROI3                 1019
#define IDC_BUTTON_ROI4                 1020
#define IDC_BUTTON_NLINES               1021
#define IDC_BUTTON_NKEYLINE             1022
#define IDC_RADIO_NORMAL                1023
#define IDC_RADIO_FULL                  1024
#define IDC_RADIO_ENVELOP               1025
#define IDC_RADIO_FILL                  1026
#define IDC_COMBO_PTSIZ                 1027
#define IDC_EDIT_UPDATERATE             1028
#define IDC_CHECK_SHOWBORDER            1029
#define IDC_CHECK_SHOWXGRID             1030
#define IDC_CHECK_SHOWXENG              1031
#define IDC_CHECK_SHOWYGRID             1032
#define IDC_EDIT_NUMGRIDLIN             1033
#define IDC_CHECK_SHOWSTATBAR           1034
#define IDC_CHECK_SHOWSTATPAGE          1035
#define IDC_RADIO_ROICURINFO            1036
#define IDC_RADIO_SPECINFO              1037
#define IDC_BUTTON_DEFAULT              1038
#define IDC_ANALYSISEDITOR1             1039
#define IDC_BUTTON_LOAD                 1040
#define IDC_REPORTVIEWER1               1041
#define IDC_EDIT_STITLE                 1042
#define IDC_EDIT_NAME                   1043
#define IDC_EDIT_QTY                    1044
#define IDC_EDIT_UNC                    1045
#define IDC_EDIT_SDESC                  1046
#define IDC_EDIT_SID                    1047
#define IDC_EDIT_TYPE                   1048
#define IDC_EDIT_UNITS                  1049
#define IDC_EDIT_ACQSTTIM               1050
#define IDC_LIST1                       1051
#define IDC_STATIC_ENGCAL               1052
#define IDC_STATIC_FWHMCAL              1053
#define IDC_STATIC_LOTAILCAL            1054
#define IDC_CHECK_LABELS                1055
#define IDC_RADIO_ASCEND                1056
#define IDC_RADIO_DESCD                 1057
#define IDC_CHECK_INFO                  1058
#define IDC_CHECK_ACTIVITY              1059
#define IDC_RADIO_LIBLINES              1060
#define IDC_RADIO_ANALYSIS              1061
#define IDC_EDIT_LIBNAME                1062
#define IDM_FILE_OPEN                   32771
#define IDM_FILE_SAVE                   32772
#define IDM_FILE_SAVEAS                 32773
#define IDM_FILE_EXIT                   32774
#define IDM_FILE_CLOSE                  32775
#define IDM_FILE_CLOSEALL               32777
#define IDM_MCA_ACQSETUP                32778
#define IDM_MCA_ACQSTART                32779
#define IDM_MCA_ACQSTOP                 32780
#define IDM_MCA_ACQCLEAR                32782
#define IDM_MCA_ADJUST                  32783
#define IDM_DISPLAY_EXPAND              32784
#define IDM_DISPLAY_ZOOM_MODE           32786
#define IDM_DISPLAY_ZOOM_OUT            32787
#define IDM_DISPLAY_SCALE_LOG           32789
#define IDM_DISPLAY_SCALE_LINEAR        32790
#define IDM_DISPLAY_SCALE_AUTO          32791
#define IDM_DISPLAY_RIOS_NEXT           32792
#define IDM_DISPLAY_RIOS_PREV           32793
#define IDM_DISPLAY_RIOS_ADD            32794
#define IDM_DISPLAY_ROIS_DEL            32795
#define IDM_DISPLAY_RIOS_CLEAR          32796
#define IDM_DISPLAY_RIOS_LOAD           32797
#define IDM_DISPLAY_RIOS_STORE          32798
#define IDM_DISPLAY_NUCLINES_SHOW       32799
#define IDM_DISPLAY_NUCLINES_NNUC       32800
#define IDM_DISPLAY_NUCLINES_PNUC       32801
#define IDM_DISPLAY_NUCLINES_NLINE      32802
#define IDM_DISPLAY_NUCLINES_PLINE      32803
#define IDM_DISPLAY_PREF                32804
#define IDM_ANALYSIS_EDITSEQ            32806
#define IDM_ANALYSIS_EXECUTE            32807
#define IDM_ANALYSIS_EXECURR            32808
#define IDM_ANALYSIS_SHOWREPORT         32809
#define IDM_ANALYSIS_PRINTREPORT        32810
#define IDM_ANALYSIS_COPYREPORT         32811
#define IDM_ANALYSYS_COPYSELECTED       32812
#define IDM_ANALYSIS_SAVEREPORT         32813
#define IDM_DATASOURCE_NEXT             32814
#define IDM_DATASOURCE_PREV             32815
#define IDM_EDIT_CFE                    32816
#define IDM_EDIT_SHOWCALIB              32817
#define IDM_EDIT_SAMPLEEDITOR           32818
#define IDM_FILE_COPY                   32819
#define IDM_FILE_EXPORT                 32820
#define IDM_FILE_PRINT                  32821
#define IDM_TEST                        32822
#define IDM_ANALYSIS_Test               32823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
